// Package graphql provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package graphql

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	AdminSecretScopes = "adminSecret.Scopes"
)

// Defines values for PgCreateDeletePermissionType.
const (
	PgCreateDeletePermissionTypePgCreateDeletePermission PgCreateDeletePermissionType = "pg_create_delete_permission"
)

// Defines values for PgCreateInsertPermissionType.
const (
	PgCreateInsertPermissionTypePgCreateInsertPermission PgCreateInsertPermissionType = "pg_create_insert_permission"
)

// Defines values for PgCreateSelectPermissionType.
const (
	PgCreateSelectPermissionTypePgCreateSelectPermission PgCreateSelectPermissionType = "pg_create_select_permission"
)

// Defines values for PgCreateUpdatePermissionType.
const (
	PgCreateUpdatePermissionTypePgCreateUpdatePermission PgCreateUpdatePermissionType = "pg_create_update_permission"
)

// Defines values for PgDropDeletePermissionType.
const (
	PgDropDeletePermissionTypePgDropDeletePermission PgDropDeletePermissionType = "pg_drop_delete_permission"
)

// Defines values for PgDropInsertPermissionType.
const (
	PgDropInsertPermissionTypePgDropInsertPermission PgDropInsertPermissionType = "pg_drop_insert_permission"
)

// Defines values for PgDropSelectPermissionType.
const (
	PgDropSelectPermissionTypePgDropSelectPermission PgDropSelectPermissionType = "pg_drop_select_permission"
)

// Defines values for PgDropUpdatePermissionType.
const (
	PgDropUpdatePermissionTypePgDropUpdatePermission PgDropUpdatePermissionType = "pg_drop_update_permission"
)

// Defines values for SqlMigrationStepType.
const (
	RunSql SqlMigrationStepType = "run_sql"
)

// Defines values for TrackTableStepType.
const (
	PgTrackTable TrackTableStepType = "pg_track_table"
)

// BoolExp Boolean expression for filtering rows
type BoolExp = map[string]interface{}

// ColumnPresets Column preset values
type ColumnPresets = map[string]interface{}

// DeletePermissionArgs defines model for DeletePermissionArgs.
type DeletePermissionArgs struct {
	// Comment Comment for the permission
	Comment    *string `json:"comment,omitempty"`
	Permission struct {
		// Filter Boolean expression for filtering rows
		Filter BoolExp `json:"filter"`
	} `json:"permission"`

	// Role Role name for the permission
	Role RolePermission `json:"role"`

	// Source Name of the source database
	Source string          `json:"source"`
	Table  TableIdentifier `json:"table"`
}

// DropPermissionArgs defines model for DropPermissionArgs.
type DropPermissionArgs struct {
	// Role Role name for the permission
	Role RolePermission `json:"role"`

	// Source Name of the source database
	Source string          `json:"source"`
	Table  TableIdentifier `json:"table"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Detailed error message
	Message *string `json:"message,omitempty"`
}

// InsertPermissionArgs defines model for InsertPermissionArgs.
type InsertPermissionArgs struct {
	// Comment Comment for the permission
	Comment    *string `json:"comment,omitempty"`
	Permission struct {
		// BackendOnly When set to true, the permission is only applied from trusted backends
		BackendOnly *bool `json:"backend_only,omitempty"`

		// Check Boolean expression for filtering rows
		Check BoolExp `json:"check"`

		// Columns List of columns to allow inserting into
		Columns *[]string `json:"columns,omitempty"`

		// Set Column preset values
		Set *ColumnPresets `json:"set,omitempty"`
	} `json:"permission"`

	// Role Role name for the permission
	Role RolePermission `json:"role"`

	// Source Name of the source database
	Source string          `json:"source"`
	Table  TableIdentifier `json:"table"`
}

// MigrationRequest defines model for MigrationRequest.
type MigrationRequest struct {
	// Datasource The data source to use
	Datasource string `json:"datasource"`

	// Down Steps to execute to revert the migration
	Down *[]MigrationStep `json:"down,omitempty"`

	// Name Name of the migration
	Name string `json:"name"`

	// Up Steps to execute for the migration
	Up []MigrationStep `json:"up"`
}

// MigrationStep defines model for MigrationStep.
type MigrationStep struct {
	union json.RawMessage
}

// PgCreateDeletePermission defines model for PgCreateDeletePermission.
type PgCreateDeletePermission struct {
	Args DeletePermissionArgs `json:"args"`

	// Type Type of operation
	Type PgCreateDeletePermissionType `json:"type"`
}

// PgCreateDeletePermissionType Type of operation
type PgCreateDeletePermissionType string

// PgCreateInsertPermission defines model for PgCreateInsertPermission.
type PgCreateInsertPermission struct {
	Args InsertPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgCreateInsertPermissionType `json:"type"`
}

// PgCreateInsertPermissionType Type of operation
type PgCreateInsertPermissionType string

// PgCreateSelectPermission defines model for PgCreateSelectPermission.
type PgCreateSelectPermission struct {
	Args SelectPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgCreateSelectPermissionType `json:"type"`
}

// PgCreateSelectPermissionType Type of operation
type PgCreateSelectPermissionType string

// PgCreateUpdatePermission defines model for PgCreateUpdatePermission.
type PgCreateUpdatePermission struct {
	Args UpdatePermissionArgs `json:"args"`

	// Type Type of operation
	Type PgCreateUpdatePermissionType `json:"type"`
}

// PgCreateUpdatePermissionType Type of operation
type PgCreateUpdatePermissionType string

// PgDropDeletePermission defines model for PgDropDeletePermission.
type PgDropDeletePermission struct {
	Args DropPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgDropDeletePermissionType `json:"type"`
}

// PgDropDeletePermissionType Type of operation
type PgDropDeletePermissionType string

// PgDropInsertPermission defines model for PgDropInsertPermission.
type PgDropInsertPermission struct {
	Args DropPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgDropInsertPermissionType `json:"type"`
}

// PgDropInsertPermissionType Type of operation
type PgDropInsertPermissionType string

// PgDropSelectPermission defines model for PgDropSelectPermission.
type PgDropSelectPermission struct {
	Args DropPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgDropSelectPermissionType `json:"type"`
}

// PgDropSelectPermissionType Type of operation
type PgDropSelectPermissionType string

// PgDropUpdatePermission defines model for PgDropUpdatePermission.
type PgDropUpdatePermission struct {
	Args DropPermissionArgs `json:"args"`

	// Type Type of operation
	Type PgDropUpdatePermissionType `json:"type"`
}

// PgDropUpdatePermissionType Type of operation
type PgDropUpdatePermissionType string

// RolePermission Role name for the permission
type RolePermission = string

// SelectPermissionArgs defines model for SelectPermissionArgs.
type SelectPermissionArgs struct {
	// Comment Comment for the permission
	Comment    *string `json:"comment,omitempty"`
	Permission struct {
		// AllowAggregations Allow aggregate queries
		AllowAggregations *bool `json:"allow_aggregations,omitempty"`

		// Columns List of columns to allow selecting
		Columns *[]string `json:"columns,omitempty"`

		// Filter Boolean expression for filtering rows
		Filter BoolExp `json:"filter"`

		// Limit Maximum number of rows that can be returned
		Limit *int `json:"limit,omitempty"`
	} `json:"permission"`

	// Role Role name for the permission
	Role RolePermission `json:"role"`

	// Source Name of the source database
	Source string          `json:"source"`
	Table  TableIdentifier `json:"table"`
}

// SqlMigrationArgs defines model for SqlMigrationArgs.
type SqlMigrationArgs struct {
	// Cascade Whether to cascade the operation
	Cascade *bool `json:"cascade,omitempty"`

	// ReadOnly Whether the operation is read-only
	ReadOnly *bool `json:"read_only,omitempty"`

	// Source The data source name
	Source string `json:"source"`

	// Sql SQL statement to execute
	Sql string `json:"sql"`
}

// SqlMigrationStep defines model for SqlMigrationStep.
type SqlMigrationStep struct {
	Args SqlMigrationArgs `json:"args"`

	// Type Type of migration step
	Type SqlMigrationStepType `json:"type"`
}

// SqlMigrationStepType Type of migration step
type SqlMigrationStepType string

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Name The name of the created migration with a timestamp
	Name *string `json:"name,omitempty"`
}

// TableIdentifier defines model for TableIdentifier.
type TableIdentifier struct {
	// Name Table name
	Name string `json:"name"`

	// Schema Schema name
	Schema string `json:"schema"`
}

// TrackTableArgs defines model for TrackTableArgs.
type TrackTableArgs struct {
	// Source The data source name
	Source string `json:"source"`
	Table  struct {
		// Name Name of the table
		Name string `json:"name"`

		// Schema Schema of the table
		Schema string `json:"schema"`
	} `json:"table"`
}

// TrackTableStep defines model for TrackTableStep.
type TrackTableStep struct {
	Args TrackTableArgs `json:"args"`

	// Type Type of migration step
	Type TrackTableStepType `json:"type"`
}

// TrackTableStepType Type of migration step
type TrackTableStepType string

// UpdatePermissionArgs defines model for UpdatePermissionArgs.
type UpdatePermissionArgs struct {
	// Comment Comment for the permission
	Comment    *string `json:"comment,omitempty"`
	Permission struct {
		// Check Boolean expression for filtering rows
		Check BoolExp `json:"check"`

		// Columns List of columns to allow updating
		Columns *[]string `json:"columns,omitempty"`

		// Filter Boolean expression for filtering rows
		Filter BoolExp `json:"filter"`

		// Set Column preset values
		Set *ColumnPresets `json:"set,omitempty"`
	} `json:"permission"`

	// Role Role name for the permission
	Role RolePermission `json:"role"`

	// Source Name of the source database
	Source string          `json:"source"`
	Table  TableIdentifier `json:"table"`
}

// MetadataOperationJSONBody defines parameters for MetadataOperation.
type MetadataOperationJSONBody struct {
	union json.RawMessage
}

// ExecuteMigrationJSONRequestBody defines body for ExecuteMigration for application/json ContentType.
type ExecuteMigrationJSONRequestBody = MigrationRequest

// MetadataOperationJSONRequestBody defines body for MetadataOperation for application/json ContentType.
type MetadataOperationJSONRequestBody MetadataOperationJSONBody

// AsSqlMigrationStep returns the union data inside the MigrationStep as a SqlMigrationStep
func (t MigrationStep) AsSqlMigrationStep() (SqlMigrationStep, error) {
	var body SqlMigrationStep
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSqlMigrationStep overwrites any union data inside the MigrationStep as the provided SqlMigrationStep
func (t *MigrationStep) FromSqlMigrationStep(v SqlMigrationStep) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSqlMigrationStep performs a merge with any union data inside the MigrationStep, using the provided SqlMigrationStep
func (t *MigrationStep) MergeSqlMigrationStep(v SqlMigrationStep) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackTableStep returns the union data inside the MigrationStep as a TrackTableStep
func (t MigrationStep) AsTrackTableStep() (TrackTableStep, error) {
	var body TrackTableStep
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackTableStep overwrites any union data inside the MigrationStep as the provided TrackTableStep
func (t *MigrationStep) FromTrackTableStep(v TrackTableStep) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackTableStep performs a merge with any union data inside the MigrationStep, using the provided TrackTableStep
func (t *MigrationStep) MergeTrackTableStep(v TrackTableStep) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MigrationStep) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MigrationStep) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ExecuteMigrationWithBody request with any body
	ExecuteMigrationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecuteMigration(ctx context.Context, body ExecuteMigrationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MetadataOperationWithBody request with any body
	MetadataOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	MetadataOperation(ctx context.Context, body MetadataOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ExecuteMigrationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteMigrationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteMigration(ctx context.Context, body ExecuteMigrationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteMigrationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataOperationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataOperation(ctx context.Context, body MetadataOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataOperationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExecuteMigrationRequest calls the generic ExecuteMigration builder with application/json body
func NewExecuteMigrationRequest(server string, body ExecuteMigrationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecuteMigrationRequestWithBody(server, "application/json", bodyReader)
}

// NewExecuteMigrationRequestWithBody generates requests for ExecuteMigration with any type of body
func NewExecuteMigrationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apis/migrate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMetadataOperationRequest calls the generic MetadataOperation builder with application/json body
func NewMetadataOperationRequest(server string, body MetadataOperationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMetadataOperationRequestWithBody(server, "application/json", bodyReader)
}

// NewMetadataOperationRequestWithBody generates requests for MetadataOperation with any type of body
func NewMetadataOperationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ExecuteMigrationWithBodyWithResponse request with any body
	ExecuteMigrationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteMigrationR, error)

	ExecuteMigrationWithResponse(ctx context.Context, body ExecuteMigrationJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteMigrationR, error)

	// MetadataOperationWithBodyWithResponse request with any body
	MetadataOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MetadataOperationR, error)

	MetadataOperationWithResponse(ctx context.Context, body MetadataOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*MetadataOperationR, error)
}

type ExecuteMigrationR struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ExecuteMigrationR) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecuteMigrationR) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MetadataOperationR struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r MetadataOperationR) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataOperationR) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ExecuteMigrationWithBodyWithResponse request with arbitrary body returning *ExecuteMigrationR
func (c *ClientWithResponses) ExecuteMigrationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteMigrationR, error) {
	rsp, err := c.ExecuteMigrationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteMigrationR(rsp)
}

func (c *ClientWithResponses) ExecuteMigrationWithResponse(ctx context.Context, body ExecuteMigrationJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteMigrationR, error) {
	rsp, err := c.ExecuteMigration(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteMigrationR(rsp)
}

// MetadataOperationWithBodyWithResponse request with arbitrary body returning *MetadataOperationR
func (c *ClientWithResponses) MetadataOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MetadataOperationR, error) {
	rsp, err := c.MetadataOperationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataOperationR(rsp)
}

func (c *ClientWithResponses) MetadataOperationWithResponse(ctx context.Context, body MetadataOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*MetadataOperationR, error) {
	rsp, err := c.MetadataOperation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataOperationR(rsp)
}

// ParseExecuteMigrationR parses an HTTP response from a ExecuteMigrationWithResponse call
func ParseExecuteMigrationR(rsp *http.Response) (*ExecuteMigrationR, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecuteMigrationR{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseMetadataOperationR parses an HTTP response from a MetadataOperationWithResponse call
func ParseMetadataOperationR(rsp *http.Response) (*MetadataOperationR, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataOperationR{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
