---
name: "release"
on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/wf_check.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_CORE_ACCOUNT_ID }}
      NIX_CACHE_PUB_KEY: ${{ secrets.NIX_CACHE_PUB_KEY }}
      NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}

  build_artifacts:
    strategy:
      matrix:
        GOOS: ["darwin", "linux"]
        GOARCH: ["amd64", "arm64"]
    uses: ./.github/workflows/wf_build_artifacts.yaml
    with:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
      VERSION: ${{ github.ref_name }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_CORE_ACCOUNT_ID }}
      NIX_CACHE_PUB_KEY: ${{ secrets.NIX_CACHE_PUB_KEY }}
      NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}

  publish:
    uses: ./.github/workflows/wf_publish.yaml
    needs:
      - tests
      - build_artifacts
    with:
      VERSION: ${{ github.ref_name }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_CORE_ACCOUNT_ID }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
